### ISSUE TITLE
Extended XP bar

### ISSUE THREAD

**Issue by arthurpaulino** [DungeonPaper/dungeon-paper-app#10]
The XP bar can go above the limit to level up because in order to level up the player has to do the `Level up` move. If the character has more experience points than the limit to level up, the excess will be added to the amount of experience that the character has on the new level.

But on the app, the XP bar cannot go above the limit and the only option, for now, is to level up immediately when the character reaches that limit.

**Comment by chenasraf** [comment]
Definitely room for improvement for that whole area. I'm considering adding something like a session log, with ability to mark XP, which will work out most of the logic there (something like "pending" XP points that will transfer once "session over" is used)

**Comment by chenasraf** [comment]
Fixed in v2.0
