### ISSUE TITLE
[FEATURE] Configure FVM for the Project

### ISSUE THREAD

**Issue by KernelPanic92** [DungeonPaper/dungeon-paper-app#18]
**Is your feature request related to a problem? Please describe.**
The current project does not utilize FVM for managing Flutter versions, leading to potential version conflicts and a lack of version consistency. Manually changing Flutter versions for the project is a tedious, time-consuming, and inconvenient process, adding to the problem.

**Describe the solution you'd like**
I'd like to propose implementing FVM (Flutter Version Management) for the project. This will help us isolate Flutter versions used in the project and streamline version management.

**Describe alternatives you've considered**
No alternative solutions have been considered as FVM is a widely-accepted tool for Flutter version management.

**Additional context**
[FVM Homepage](https://fvm.app/)

Proposed Steps:
- Install FVM in your development environment.
- Configure the desired Flutter version for the project using FVM.
- Update the `.fvmrc` or `fvm_config.yaml` file in the project with the Flutter version information.

**Comment by chenasraf** [comment]
I would be happy if you gave it a go if you are able. If not, I will do my best to add it quickly, but it might take a few days

**Comment by KernelPanic92** [comment]
@chenasraf What Flutter version are you using for this project? `2.13.0-0.2.pre`?

**Comment by chenasraf** [comment]
Last build was with the current stable at the time, 3.13.5

**Comment by chenasraf** [comment]
Fixed in 91b5502033bb3004ac70541bd2118616267b3621
