### ISSUE TITLE
Avoiding some pop-ups

### ISSUE THREAD

**Issue by arthurpaulino** [DungeonPaper/dungeon-paper-app#9]
When we are in an activity and we want to go back, the app almost always pops up a dialog asking me if I am sure to proceed and says that unsaved data will be lost or something like that. However, the pop up is unnecessary if I haven't even edited anything, do you agree?

So, instead of always making pop ups appear, I think it would be interesting to check whether the user has any information he/she doesn't want to lose in the first place. Has the user written something? Has the user checked some box? Those kinds of tests.

**Comment by chenasraf** [comment]
Yes, I've been meaning to clean up that logic. I need to use dirty markers on the data to avoid unnecessary popups.

**Comment by chenasraf** [comment]
I've recently decided to rework the character edit screen, to be more in-line with the new custom classes screen. This will omit the need for most confirmations as only valid inputs will be savable, and only one confirmation would need to show up once the state is dirty.

I'll update and close this issue once I'm done with the changes.
